// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WpfApp.Data;

namespace WpfApp.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20220404153449_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WpfApp.Models.FileReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GeneralInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid?>("_GeneralInfoId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GeneralInfoId");

                    b.HasIndex("_GeneralInfoId1");

                    b.ToTable("FileRepots");
                });

            modelBuilder.Entity("WpfApp.Models.GeneralInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfFire")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrganCode")
                        .HasColumnType("text");

                    b.Property<string>("TypeOfFireDepSettlement")
                        .HasColumnType("text");

                    b.Property<string>("TypeOfSettlement")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeneralInformations");
                });

            modelBuilder.Entity("WpfApp.Models.FileReport", b =>
                {
                    b.HasOne("WpfApp.Models.GeneralInformation", "GeneralInfo")
                        .WithMany()
                        .HasForeignKey("GeneralInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WpfApp.Models.GeneralInformation", "_GeneralInfo")
                        .WithMany()
                        .HasForeignKey("_GeneralInfoId1");
                });
#pragma warning restore 612, 618
        }
    }
}
